# Generated by Django 4.2.11 on 2026-06-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='simplify_debts',
            field=models.BooleanField(default=True),
        ),
    ]
